# Generated by Django 2.2.5 on 2019-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndelements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('effects', models.CharField(max_length=1000)),
            ],
        ),
    ]
