# Generated by Django 2.2.5 on 2019-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndelements', '0002_auto_20190927_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='users',
        ),
        migrations.RemoveField(
            model_name='player',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='dndelements.Player'),
        ),
    ]
