# Generated by Django 2.2.5 on 2019-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndelements', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='rpg_variant',
        ),
    ]
