# Generated by Django 2.2.5 on 2019-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndelements', '0003_auto_20190927_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
