# Generated by Django 2.2.5 on 2019-09-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndelements', '0005_bonus_itembonus_statlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statlist',
            name='character',
        ),
        migrations.AddField(
            model_name='player',
            name='player_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dndelements.StatList'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dndelements.PlayerClass'),
        ),
    ]
