# Generated by Django 2.2.5 on 2019-09-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_auto_20190923_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
